Fix broken TestNodeUnpublishVolume cases
Two test failures were exposed in the previous commit by calling the
mock controller's finisher. They are fixed here as follows:

```
    --- FAIL: TestNodeUnpublishVolume/success:_unpublish_with_already_unmounted_target (0.00s)
        node_test.go:478: missing call(s) to *mocks.MockMounter.Unmount(is equal to /target/path) /home/efried/go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver/node_test.go:472
        node_test.go:478: aborting test due to missing call(s)
```

The `Unmount` call should not have been `EXPECT`ed because `NodeUnpublishVolume`
[returns early](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/0ae998c5a95fe6dbee7f43c182997e64872695e6/pkg/driver/node.go#L176-L182)
if `GetDeviceName` returns a zero refcount. Remove the expected call.

```
    --- FAIL: TestNodeUnpublishVolume/fail:_mounter_failed_to_GetDeviceName (0.00s)
        node_test.go:557: missing call(s) to *mocks.MockMounter.Unmount(is equal to /target/path) /home/efried/go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver/node_test.go:551
        node_test.go:557: aborting test due to missing call(s)
```

The `Unmount` call should not have been `EXPECT`ed because when `GetDeviceName` fails, `NodeUnpublishVolume`
[fails early](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/0ae998c5a95fe6dbee7f43c182997e64872695e6/pkg/driver/node.go#L167-L174),
before it gets to the `Unmount` call. Remove the expected call.